# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: My profile
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "" # the subpath of the site
url: "https://hotelshoe27.github.io" # the base hostname & protocol for the site
og_image: /assets/img/my_profile.png
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: About Me
      slug: /
    - name: Experience
      slug: /experience
    - name: Publication
      slug: /publication
footer:
  show_powered_by: false
  contact:
    - name: Email
      value: edensth@naver.com (local)
      link: mailto:edensth@naver.com
    - name: Email
      value: edensth@gmail.com (global)
      link: mailto:edensth@gmail.com
  follow:
    - name: GitHub
      link: https://github.com/hotelshoe27
    - name: Tistory
      link: https://prlabhotelshoe.tistory.com/
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
